# Generated by Django 4.1.5 on 2023-08-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0040_alter_site_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('did', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='DID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='MID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to='api.userprofile', verbose_name='Author')),
                ('documents', models.ManyToManyField(blank=True, related_name='document', to='message.document', verbose_name='Documents')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_user', to='api.userprofile', verbose_name='Recipient')),
            ],
        ),
    ]
