# Generated by Django 4.1.5 on 2023-08-04 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('mtid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='MTID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_type', to='message.messagetype', verbose_name='Documents'),
        ),
    ]
