# Generated by Django 4.1.5 on 2023-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('message', '0002_messagetype_remove_message_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='message',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='document', to='media.document', verbose_name='Documents'),
        ),
    ]
