# Generated by Django 4.1.5 on 2023-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_report_remove_document_author_remove_document_user'),
        ('message', '0003_delete_document_alter_message_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='documents',
        ),
        migrations.AddField(
            model_name='message',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to='media.report', verbose_name='Reports'),
        ),
    ]
