# Generated by Django 4.1.5 on 2023-08-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_rename_connection_request_connection_relation'),
        ('message', '0004_remove_message_documents_message_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_connection', to='workflows.connection', verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_type', to='message.messagetype', verbose_name='Type'),
        ),
    ]
