# Generated by Django 4.1.5 on 2023-08-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_alter_connection_state'),
        ('message', '0005_message_connection_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_connection', to='workflows.connection', verbose_name='Connection'),
        ),
    ]
