# Generated by Django 4.1.5 on 2023-08-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='subject',
        ),
    ]
