# Generated by Django 4.1.5 on 2023-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_rename_text_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
    ]
