# Generated by Django 4.1.5 on 2023-07-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0040_alter_site_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('uroid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='UROID')),
                ('account_create', models.BooleanField(default=False, verbose_name='Account Create')),
                ('privilege_set', models.BooleanField(default=False, verbose_name='Privilege Set')),
                ('crop_c', models.BooleanField(default=False, verbose_name='Crop Create')),
                ('crop_r', models.BooleanField(default=False, verbose_name='Crop Read')),
                ('crop_u', models.BooleanField(default=False, verbose_name='Crop Update')),
                ('crop_d', models.BooleanField(default=False, verbose_name='Crop Delete')),
                ('site_c', models.BooleanField(default=False, verbose_name='Site Create')),
                ('site_r', models.BooleanField(default=False, verbose_name='Site Read')),
                ('site_u', models.BooleanField(default=False, verbose_name='Site Update')),
                ('site_d', models.BooleanField(default=False, verbose_name='Site Delete')),
                ('chem_c', models.BooleanField(default=False, verbose_name='ChemTable Create')),
                ('chem_r', models.BooleanField(default=False, verbose_name='ChemTable Read')),
                ('chem_u', models.BooleanField(default=False, verbose_name='ChemTable Update')),
                ('chem_d', models.BooleanField(default=False, verbose_name='ChemTable Delete')),
                ('purchase_c', models.BooleanField(default=False, verbose_name='Purchase Create')),
                ('purchase_r', models.BooleanField(default=False, verbose_name='Purchase Read')),
                ('purchase_u', models.BooleanField(default=False, verbose_name='Purchase Update')),
                ('purchase_d', models.BooleanField(default=False, verbose_name='Purchase Delete')),
                ('equip_c', models.BooleanField(default=False, verbose_name='Equipment Create')),
                ('equip_r', models.BooleanField(default=False, verbose_name='Equipment Read')),
                ('equip_u', models.BooleanField(default=False, verbose_name='Equipment Update')),
                ('equip_d', models.BooleanField(default=False, verbose_name='Equipment Delete')),
                ('spray_r', models.BooleanField(default=False, verbose_name='Spray Data Read')),
                ('spraycard_c', models.BooleanField(default=False, verbose_name='Spray Card Create')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to='api.userprofile', verbose_name='User')),
            ],
        ),
    ]
