# Generated by Django 4.1.5 on 2023-07-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_site_crop'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserPrivilege',
        ),
    ]
