# Generated by Django 4.1.5 on 2023-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_userrole_userprivilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='spraycard_a',
            field=models.BooleanField(default=False, verbose_name='Spray Card Assign'),
        ),
    ]
