# Generated by Django 4.1.5 on 2023-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userprivilege_spraycard_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivilege',
            name='account_create',
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='client_add',
            field=models.BooleanField(default=True, verbose_name='Client Add'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='client_r',
            field=models.BooleanField(default=True, verbose_name='Client Read'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='employee_c',
            field=models.BooleanField(default=True, verbose_name='Employee Create'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='employee_r',
            field=models.BooleanField(default=True, verbose_name='Employee Read'),
        ),
    ]
