# Generated by Django 4.1.5 on 2023-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_userprivilege_account_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivilege',
            name='client_add',
            field=models.BooleanField(default=False, verbose_name='Client Add'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='client_r',
            field=models.BooleanField(default=False, verbose_name='Client Read'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='employee_c',
            field=models.BooleanField(default=False, verbose_name='Employee Create'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='employee_r',
            field=models.BooleanField(default=False, verbose_name='Employee Read'),
        ),
    ]
