# Generated by Django 4.1.5 on 2023-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userprivilege_client_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='client_d',
            field=models.BooleanField(default=False, verbose_name='Client Delete'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='employee_d',
            field=models.BooleanField(default=False, verbose_name='Employee Delete'),
        ),
    ]
