# Generated by Django 4.1.5 on 2023-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_userprivilege_client_d_userprivilege_employee_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='spray_u',
            field=models.BooleanField(default=False, verbose_name='Spray Data Update'),
        ),
    ]
