# Generated by Django 4.1.5 on 2023-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_userprivilege_spray_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='report_c',
            field=models.BooleanField(default=False, verbose_name='Report Create'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='report_d',
            field=models.BooleanField(default=False, verbose_name='Report Delete'),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='report_r',
            field=models.BooleanField(default=False, verbose_name='Report Read'),
        ),
    ]
