# Generated by Django 4.1.5 on 2023-08-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_userprivilege_report_c_userprivilege_report_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='business_u',
            field=models.BooleanField(default=False, verbose_name='Business Update'),
        ),
    ]
