# Generated by Django 4.1.6 on 2023-02-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='UID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Actual Name')),
                ('business_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Business Name')),
                ('registration_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='Registration No.')),
                ('reg_expire_date', models.DateField(blank=True, null=True, verbose_name='Registration Expire Date')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=64, null=True, verbose_name='County')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('cell', models.CharField(blank=True, max_length=32, null=True, verbose_name='Cell Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('self_activated', models.BooleanField(default=False, verbose_name='Self Activated')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_added_by', to='api.user', verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationType',
            fields=[
                ('urtid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URTID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('utid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='UTID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('urid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_added_by', to='api.user', verbose_name='Added By')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_user', to='api.user', verbose_name='Provider')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationtype', to='api.userrelationtype', verbose_name='Relation Type')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_user', to='api.user', verbose_name='Requester')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_type', to='api.usertype', verbose_name='User Type'),
        ),
    ]
