# Generated by Django 4.1.5 on 2023-02-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelation',
            old_name='relation_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Is Resolved'),
        ),
    ]
