# Generated by Django 4.1.6 on 2023-02-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipmenttype_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('ccid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CCID')),
                ('name', models.CharField(max_length=128, verbose_name='Crop Name')),
                ('category', models.CharField(max_length=128, verbose_name='Category Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('cvid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CVID')),
                ('name', models.CharField(max_length=128, verbose_name='Crop Variety')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variety_category', to='api.cropcategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='CropLifecycle',
            fields=[
                ('clcid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CLCID')),
                ('name', models.CharField(max_length=128, verbose_name='Lifecycle Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_category', to='api.cropcategory', verbose_name='Crop Name')),
            ],
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('cgsid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CGSID')),
                ('name', models.CharField(max_length=128, verbose_name='Stage Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_stage_category', to='api.cropcategory', verbose_name='Crop Name')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_category', to='api.cropcategory', verbose_name='Crop Name')),
                ('growth_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_growth_stage', to='api.cropgrowthstage', verbose_name='Grow Stage')),
                ('lifecycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_lifecycle', to='api.croplifecycle', verbose_name='Lifecycle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_user', to='api.user', verbose_name='User')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_variety', to='api.cropvariety', verbose_name='Variety')),
            ],
        ),
    ]
