# Generated by Django 4.1.5 on 2023-02-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cropcategory_cropvariety_croplifecycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='lifecycle',
        ),
        migrations.AddField(
            model_name='cropcategory',
            name='crop_code',
            field=models.CharField(default='A', max_length=16, verbose_name='Crop Code'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CropLifecycle',
        ),
    ]
