# Generated by Django 4.1.5 on 2023-05-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicationrecord_assign_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_crop', to='api.crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chem_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_crop', to='api.crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_chem', to='api.chemical', verbose_name='Chemical'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='site',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_crop', to='api.crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='site',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_user', to='api.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_added_by', to='api.userprofile', verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_user', to='api.userprofile', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_user', to='api.userprofile', verbose_name='Requester'),
        ),
    ]
