# Generated by Django 4.1.5 on 2023-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitetype_unit_usertype_note_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='usage',
            field=models.SmallIntegerField(choices=[(1, 'Site'), (2, 'Chemical')], verbose_name='Level'),
        ),
    ]
