# Generated by Django 4.1.5 on 2023-05-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
