# Generated by Django 4.1.5 on 2023-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='self_activated',
            field=models.BooleanField(default=True, verbose_name='Self Activated'),
        ),
    ]
