# Generated by Django 4.1.6 on 2023-02-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_unit_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('chemid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ChemID')),
                ('type', models.CharField(max_length=128, verbose_name='Trade Name')),
                ('trade_name', models.CharField(max_length=128, verbose_name='Trade Name')),
                ('company', models.CharField(max_length=128, verbose_name='Company')),
                ('epa_reg_no', models.CharField(max_length=32, verbose_name='EPA Registration No.')),
                ('active_ingredient', models.CharField(max_length=128, verbose_name='Active Ingredient')),
                ('percent_ai', models.CharField(max_length=128, verbose_name='Active Ingredient Percent')),
                ('rei', models.FloatField(verbose_name='REI')),
                ('phi', models.IntegerField(verbose_name='PHI')),
                ('labeled_crops', models.CharField(blank=True, max_length=256, null=True, verbose_name='Labeled Crops')),
                ('restricted_use', models.BooleanField(verbose_name='Is Active')),
                ('label_image', models.CharField(blank=True, max_length=128, null=True, verbose_name='Labeled Image')),
                ('imported_from', models.CharField(blank=True, max_length=32, null=True, verbose_name='Imported From')),
                ('validated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Validated By')),
                ('entered_year', models.IntegerField(blank=True, null=True, verbose_name='Entered Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_unit', to='api.unit', verbose_name='Application Unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_user', to='api.user', verbose_name='User')),
            ],
        ),
    ]
