# Generated by Django 4.1.5 on 2023-05-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='assign_to',
        ),
    ]
