# Generated by Django 4.1.5 on 2023-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_applicationrecord_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='usertype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
