# Generated by Django 4.1.5 on 2023-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userrelation_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='update_time',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
