# Generated by Django 4.1.5 on 2023-03-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_applicationtype_decisionsupport_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='multiple_site',
        ),
        migrations.AddField(
            model_name='operationtype',
            name='multiple_records',
            field=models.BooleanField(default=False, verbose_name='Multiple Records'),
        ),
    ]
