# Generated by Django 4.1.5 on 2023-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_applicationrecord_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='application_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('withdrew', 'Withdrew'), ('completed', 'Completed')], default='initiated', max_length=20),
        ),
    ]
