# Generated by Django 4.1.5 on 2023-03-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_operation_multiple_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='app_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Application Datetime'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='water_use',
            field=models.BooleanField(default=False, verbose_name='Water Use'),
        ),
    ]
