# Generated by Django 4.1.5 on 2023-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_applicationrecord_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='application_status',
        ),
        migrations.AddField(
            model_name='operation',
            name='state',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('withdrew', 'Withdrew'), ('completed', 'Completed')], default='initiated', max_length=20),
        ),
    ]
