# Generated by Django 4.1.5 on 2023-06-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_applicationrecord_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='datetime',
        ),
    ]
