# Generated by Django 4.1.5 on 2023-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_user_reg_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
