# Generated by Django 4.1.5 on 2023-03-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_crop_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropcategory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='cropgrowthstage',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='create_time',
        ),
        migrations.AddField(
            model_name='cropcategory',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AddField(
            model_name='cropgrowthstage',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
    ]
