# Generated by Django 4.1.5 on 2023-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_applicationrecord_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
