# Generated by Django 4.1.6 on 2023-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_productbase_alter_cropgrowthstage_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='active_ingredient',
            field=models.CharField(max_length=256, verbose_name='Active Ingredient'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='restricted_use',
            field=models.CharField(max_length=16, verbose_name='Restricted Use'),
        ),
    ]
