# Generated by Django 4.1.5 on 2023-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_applicationrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='application_rate',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Application Rate'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='applied_area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Applied Area'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='total_amount',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='total_cost',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Total Cost'),
        ),
    ]
