# Generated by Django 4.1.5 on 2023-06-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_applicationrecord_application_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='app_date',
        ),
    ]
