# Generated by Django 4.1.6 on 2023-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_unit_create_time_unit_refresh_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='usage',
            field=models.CharField(max_length=32, verbose_name='Usage'),
        ),
    ]
