# Generated by Django 4.1.5 on 2023-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_applicationrecord_app_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='applicationrecord',
            name='start_time',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='finish_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Finish Datetime'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='harvestable_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Harvestable Datetime'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='start_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Start Datetime'),
        ),
    ]
