# Generated by Django 4.1.6 on 2023-03-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_unit_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
