# Generated by Django 4.1.5 on 2023-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_applicationrecord_finish_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='applicationrecord',
            name='water_unit',
        ),
        migrations.RemoveField(
            model_name='applicationrecord',
            name='water_use',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='gallons_water_rate',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Gallons Water Rate'),
        ),
    ]
