# Generated by Django 4.1.5 on 2023-03-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_unit_name_alter_unit_usage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBase',
            new_name='ChemicalProductBase',
        ),
    ]
