# Generated by Django 4.1.5 on 2023-06-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_applicationrecord_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='operator',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='applicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_applicator_user', to='api.userprofile', verbose_name='Applicator'),
        ),
    ]
