# Generated by Django 4.1.5 on 2023-03-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_productbase_chemicalproductbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='pbid',
            field=models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ChemPBID'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='product_type_dec',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Product Type_DEC'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='product_use_dec',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Product Use_DEC'),
        ),
    ]
