# Generated by Django 4.1.5 on 2023-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_applicationrecord_operator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='harvestable_datetime',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='harvestable_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Harvestable Date'),
        ),
    ]
