# Generated by Django 4.1.5 on 2023-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_applicationrecord_harvestable_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='license_expire_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_license_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pesticide_applicator_no',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Pesticide Certification I.D. Number '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pesticide_expire_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Pesticide Certification Expire Date'),
        ),
    ]
