# Generated by Django 4.1.5 on 2023-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_chemicalproductbase_pbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='distributor_product_name_epa',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Distributor Product Name_EPA'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='product_name_dec',
            field=models.CharField(max_length=256, verbose_name='Product Name_DEC'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='product_name_epa',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Product Name_EPA'),
        ),
    ]
