# Generated by Django 4.1.5 on 2023-03-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_chemicalproductbase_distributor_product_name_epa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='distributor_product_name_epa',
            field=models.TextField(blank=True, null=True, verbose_name='Distributor Product Name_EPA'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='distributor_reg_no_epa',
            field=models.TextField(blank=True, null=True, verbose_name='Distributor Reg No_EPA'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='pc_pt_dec',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='PC Pt_DEC'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='pc_pt_epa',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='PC Pt_EPA'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='previous_reg_no_epa',
            field=models.TextField(blank=True, null=True, verbose_name='Previous Reg No_EPA'),
        ),
    ]
