# Generated by Django 4.1.5 on 2023-06-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_userprofile_address_userprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='type',
        ),
        migrations.AddField(
            model_name='usertype',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationtype', to='api.userrelationtype', verbose_name='Relation Type'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
