# Generated by Django 4.1.5 on 2023-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_chemicalproductbase_distributor_product_name_epa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='product_type_epa',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Product Type_EPA'),
        ),
    ]
