# Generated by Django 4.1.5 on 2023-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_userrelation_type_usertype_relation_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentType',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='owner',
        ),
        migrations.AddField(
            model_name='equipment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
