# Generated by Django 4.1.5 on 2023-03-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_chemicalproductbase_product_type_epa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalproductbase',
            old_name='pbid',
            new_name='chempbid',
        ),
    ]
