# Generated by Django 4.1.5 on 2023-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_pbid_chemicalproductbase_chempbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='pc_name_dec',
            field=models.TextField(blank=True, null=True, verbose_name='PC Name_DEC'),
        ),
        migrations.AlterField(
            model_name='chemicalproductbase',
            name='pc_name_epa',
            field=models.TextField(blank=True, null=True, verbose_name='PC Name_EPA'),
        ),
    ]
