# Generated by Django 4.1.5 on 2023-06-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_site_crop_year_remove_site_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='entered_year',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='imported_from',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='validated_by',
        ),
    ]
