# Generated by Django 4.1.5 on 2023-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_chemicalproductbase_pc_name_dec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetype',
            name='create_time',
        ),
        migrations.AddField(
            model_name='sitetype',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='level',
            field=models.SmallIntegerField(verbose_name='Level'),
        ),
    ]
