# Generated by Django 4.1.5 on 2023-03-30 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_sitetype_create_time_sitetype_refresh_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_site', to='api.site', verbose_name='Parent Site'),
        ),
    ]
