# Generated by Django 4.1.5 on 2023-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_chemical_entered_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserecord',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='purchaserecord',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='cost_per_unit',
            field=models.CharField(max_length=32, verbose_name='Cost Per Applied Unit'),
        ),
    ]
