# Generated by Django 4.1.5 on 2023-03-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_site_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='size',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Size'),
        ),
    ]
