# Generated by Django 4.1.5 on 2023-06-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_purchaserecord_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecord',
            name='amount_pesticide_per_tank',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Amount Pesticide per Tank'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='partial_treatment',
            field=models.BooleanField(default=False, verbose_name='Partial Treatment'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_responsible_user', to='api.userprofile', verbose_name='Responsible Person'),
        ),
    ]
