# Generated by Django 4.1.5 on 2023-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_userprofile_cell_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecord',
            name='alt_row_middle',
            field=models.BooleanField(default=False, verbose_name='Alt Row Middle'),
        ),
    ]
