# Generated by Django 4.1.5 on 2023-03-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_site_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.CharField(default=1, max_length=64, verbose_name='Owner Name'),
            preserve_default=False,
        ),
    ]
