# Generated by Django 4.1.5 on 2023-07-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_applicationrecord_alt_row_middle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='amount_pesticide_per_tank',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Amount Pesticide Per Tank'),
        ),
    ]
