# Generated by Django 4.1.5 on 2023-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_equipment_type_alter_equipment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
