# Generated by Django 4.1.5 on 2023-04-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_equipment_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='app_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Application Datetime'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='water_use',
            field=models.CharField(default='N', max_length=16, verbose_name='Water Use'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Wind Direction'),
        ),
    ]
