# Generated by Django 4.1.5 on 2023-07-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_applicationrecord_amount_pesticide_per_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='growth_stage',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='growth_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_growth_stage', to='api.cropgrowthstage', verbose_name='Grow Stage'),
        ),
    ]
