# Generated by Django 4.1.5 on 2023-04-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_applicationrecord_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtype',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='decisionsupport',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='operationtype',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='pestsdiseases',
            name='create_time',
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AddField(
            model_name='decisionsupport',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
        migrations.AddField(
            model_name='pestsdiseases',
            name='refresh_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Refresh Time'),
        ),
    ]
