# Generated by Django 4.1.5 on 2023-04-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_applicationtype_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTarget',
            fields=[
                ('attid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ATTID')),
                ('name', models.CharField(max_length=128, verbose_name='Application Target')),
                ('code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Target Code ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('refresh_time', models.DateTimeField(auto_now=True, verbose_name='Refresh Time')),
            ],
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_pd', to='api.applicationtarget', verbose_name='Pests/Diseases'),
        ),
        migrations.DeleteModel(
            name='PestsDiseases',
        ),
    ]
