# Generated by Django 4.1.5 on 2023-04-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_applicationtarget_alter_applicationrecord_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtarget',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_category', to='api.cropcategory', verbose_name='Crop'),
        ),
    ]
