# Generated by Django 4.1.5 on 2023-04-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_applicationtarget_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='operator',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Operator'),
        ),
    ]
