# Generated by Django 4.1.5 on 2023-04-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_applicationrecord_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='customer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Customer'),
        ),
    ]
