# Generated by Django 4.1.5 on 2023-04-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_applicationrecord_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='growth_stage',
        ),
    ]
