# Generated by Django 4.1.5 on 2023-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_applicationrecord_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='water_use',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Water Use'),
        ),
    ]
