# Generated by Django 4.1.5 on 2023-04-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_applicationrecord_water_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='opid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_op', to='api.operation', verbose_name='OPID'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_pd', to='api.applicationtarget', verbose_name='Application Target'),
        ),
    ]
