# Generated by Django 4.1.6 on 2023-04-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_operation_update_time_alter_applicationrecord_opid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='area_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_area_unit', to='api.unit', verbose_name='Area Unit'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='operator',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='pur_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Purchase Datetime'),
        ),
    ]
