# Generated by Django 4.1.5 on 2023-04-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_purchaserecord_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_purchase', to='api.purchaserecord', verbose_name='Chemical'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_chem', to='api.chemical', verbose_name='Chemical'),
        ),
    ]
