# Generated by Django 4.1.6 on 2023-04-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_harvestrecord_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_crop', to='api.crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='opid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_op', to='api.operation', verbose_name='OPID'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='opid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_op', to='api.operation', verbose_name='OPID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_crop', to='api.crop', verbose_name='Crop'),
        ),
    ]
