# Generated by Django 4.1.5 on 2023-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_applicationrecord_crop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='app_datetime',
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='app_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Application Date'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='finish_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Finish Time'),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='start_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Start Time'),
        ),
    ]
