# Generated by Django 4.1.5 on 2023-05-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='registration',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
