# Generated by Django 4.1.5 on 2023-05-26 15:28

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_registration_create_time_registration_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
