# Generated by Django 4.1.5 on 2023-05-26 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0005_alter_registration_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('prpid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='PRPID')),
                ('state', django_fsm.FSMField(choices=[('request_received', 'Request Received'), ('email_sent', 'Email Sent'), ('password_updated', 'Password Updated')], default='pending', max_length=50)),
                ('token', models.CharField(default='PWD-d448ccb0-1635-4eaa-bf27-2c768ac04a08', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
