# Generated by Django 4.1.5 on 2023-05-26 22:13

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='state',
            field=django_fsm.FSMField(choices=[('request_received', 'Request Received'), ('email_sent', 'Email Sent'), ('password_updated', 'Password Updated')], default='request_received', max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='PWD-119a2f93-8e62-412b-a126-051c98a1762c', max_length=64, unique=True),
        ),
    ]
