# Generated by Django 4.1.5 on 2023-05-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_passwordreset_state_alter_passwordreset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='token',
        ),
    ]
