# Generated by Django 4.1.5 on 2023-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_passwordreset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
    ]
