# Generated by Django 4.1.5 on 2023-05-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_applicationrecord_assign_to'),
        ('workflows', '0012_spraycard_spraycardassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraycard',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder_spraycard', to='api.userprofile', verbose_name='Holder'),
        ),
        migrations.AlterField(
            model_name='spraycard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='spraycardassignment',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
