# Generated by Django 4.1.5 on 2023-06-01 02:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_alter_spraycard_holder_alter_spraycard_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraycard',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('withdrew', 'Withdrew'), ('completed', 'Completed')], default='initiated', max_length=50),
        ),
    ]
