# Generated by Django 4.1.5 on 2023-06-01 13:21

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_alter_spraycard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraycard',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('withdrew', 'Withdrew'), ('completed', 'Completed'), ('approved', 'Approved')], default='initiated', max_length=50),
        ),
    ]
