# Generated by Django 4.1.5 on 2023-06-01 17:39

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_applicationrecord_create_time_and_more'),
        ('workflows', '0015_alter_spraycard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraycard',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('withdrew', 'Withdrew'), ('completed', 'Completed'), ('archived', 'Archived')], default='initiated', max_length=50),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('cpid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CPID')),
                ('state', django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('connected', 'Connected'), ('rejected', 'Rejected')], default='initiated', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('connection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userrelation', verbose_name='Connection Request')),
            ],
        ),
    ]
