# Generated by Django 4.1.5 on 2023-06-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_operation_datetime'),
        ('workflows', '0017_alter_spraycard_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spraycard',
            name='application_record',
        ),
        migrations.AddField(
            model_name='spraycard',
            name='spray_record',
            field=models.ForeignKey(default='OPID-147fd5ef-0aa2-4ded-ac0b-06cca7ddde1e', on_delete=django.db.models.deletion.CASCADE, to='api.operation', verbose_name='Spray Record'),
            preserve_default=False,
        ),
    ]
