# Generated by Django 4.1.5 on 2023-07-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_site_crop'),
        ('workflows', '0018_remove_spraycard_application_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrate_type', to='api.usertype', verbose_name='User Type'),
        ),
    ]
