# Generated by Django 4.1.6 on 2023-09-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_site_crop'),
        ('workflows', '0021_alter_connection_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userrelation', verbose_name='Relation'),
        ),
    ]
