# Generated by Django 4.1.13 on 2024-02-02 04:25

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_alter_connection_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraycard',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('archived', 'Archived')], default='initiated', max_length=50),
        ),
    ]
