# Generated by Django 4.1.5 on 2023-08-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0040_alter_site_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('did', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='DID')),
                ('name', models.CharField(max_length=256, verbose_name='File Name')),
                ('file', models.FileField(upload_to='documents/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_author_user', to='api.userprofile', verbose_name='Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_user', to='api.userprofile', verbose_name='User')),
            ],
        ),
    ]
