# Generated by Django 4.1.5 on 2023-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='RID')),
                ('name', models.CharField(max_length=256, verbose_name='File Name')),
                ('file', models.FileField(upload_to='reports/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
