# Generated by Django 4.1.5 on 2023-08-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_site_crop'),
        ('message', '0004_remove_message_documents_message_reports'),
        ('media', '0002_report_remove_document_author_remove_document_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_author_user', to='api.userprofile', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_user', to='api.userprofile', verbose_name='User'),
        ),
    ]
